name: test_cd

on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: projetoZipado
          path: main.py
  deploy:
    runs-on: ubunto-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetoZipado
      - name: Diplay structure of download files
        run: ls -R