name: test_cd

on: 
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando CD 
        uses: actions/upload-artifact@v4
        with:
          name: projetoZip.zip
          path: |
            main.py
            '../main.py'